### ISSUE TITLE
Upload example

### ISSUE THREAD

**Issue by ertwroc** [paramaggarwal/react-dropzone#12]
Hi,
Could you create additional example how to use react-dropzone to upload file?

**Comment by greenlaw110** [comment]
I am also curious on how to get it done

**Comment by nextminds** [comment]
It's the same as you would do with file form field, but instead of getting the 'files' property from the field, you listen to the onDrop callback to handle the files. Simple explantion here: http://abandon.ie/notebook/simple-file-uploads-using-jquery-ajax

The `onDrop` provides you with an array of [Files](https://developer.mozilla.org/en-US/docs/Web/API/File) which you can then send to a server. For example, with [SuperAgent](https://github.com/visionmedia/superagent) as a http/ajax library:

```javascript```
    onDrop: function(files){
        var req = request.post('/upload');
        files.forEach((file)=> {
            req.attach(file.name, file);
        });
        req.end(callback);
    }
```

Or if you use a Flux architecture like me: for every file in the onDrop trigger an action, which will then call a function in your api-utils, which will then do the request like above, which will eventually trigger another action when complete or erroneous.

**Comment by paramaggarwal** [comment]
Closing this one. Will accommodate @nextminds note in the README so everyone can read.

**Comment by tnrich** [comment]
Hey there, I'm using superagent and following the steps @nextminds outlined, but I'm having trouble getting file upload to work (in my case it's a .xlsx file).

Has anyone else had success with this? Are there any tips to follow. I'm using express and the req.body is empty on the backend.
