### ISSUE TITLE
Remove inline styling

### ISSUE THREAD

**Issue by googamanga** [paramaggarwal/react-dropzone#42]
Please get rid of forced inline width and height styling, styling should be left to css.

Same with DragActive, it should just add / remove a class

    var style = this.props.style || {
      width: this.props.size || 100,  //get rid of these two lines please
      height: this.props.size || 100,  //get rid of these two lines please
      borderStyle: this.state.isDragActive ? 'solid' : 'dashed'
    };

**Comment by paramaggarwal** [comment]
Just pass an empty `this.props.style` as `{}`, that should solve your problem.

**Comment by robmclarty** [comment]
I reacted the same way as @googamanga; I had already setup CSS for the element where I was putting Dropzone, and then when I hooked up the library, all those styles got overridden by hard inline styles. Not at all what I was expecting.

Passing an empty object solves the above problem, but tbh it looks extremely ugly and non-intuitive. I think the default shouldn't require adding weird empty object notation.

```
<Dropzone
  className="dropzone-files"
  style={{}}
  ref="dropzone"
  onDrop={this.onDrop}
  onClick={this.selectFiles}></Dropzone>
```

I understand wanting to have a useable "out of the box" experience, but this makes the library harder to use in the real world. I doubt a production app would ever use the defaults. As a result, I suggest making these styles the exception (e.g., by passing in some kind of flag) rather than the rule. The default should be no inline styles imho.

**Comment by paramaggarwal** [comment]
I agree, could someone please raise PR with something like this, I'll merge. The idea being if either of `style` or `className` is set, then ignore the default styling.

```javascript
var style;
if (this.props.style) {
  style = this.props.style;
} else if (this.props.className) {
  style = {}
} else {
  style = {
    width: this.props.size || 100,
    height: this.props.size || 100,
    borderStyle: this.state.isDragActive ? 'solid' : 'dashed'
  }
};
```

**Comment by robmclarty** [comment]
I added a pull request with some changes to handle this in a better (imho). It retains the original functionality (because having a good "out of the box" experience is valuable) while adding a few new features to offer greater control for those who need it.

I think that listening for `className` isn't necessarily optimal as a user may want to use a mix of both inline styles and class styles. It also doesn't make it obvious what's happening (i.e., that the default `style` object is being disabled, or not).

If the intention is to "render the `Dropzone` component without the default style object", then imo this should be made more obvious: for example by explicitly declaring a `noDefaultStyles` flag. With such a flag set, my expectations would naturally be that my Dropzone element will have no CSS applied to it whatsoever that I didn't add myself, which helps with customizing it ;)

**Comment by paramaggarwal** [comment]
But to stye a component you'd need to specify either `style` or `className` and doing either of them would disable default styling in this case - isn't that what you expect here? Setting a separate flag like `noDefaultStyles` seems redundant here.

**Comment by nickhudkins** [comment]
It is entirely possible that someone may want to inline NECESSARY styles (like hiding the file input, making sure it is 100% the size of the drop zone.... or something of that nature) while defining a className as a hook for a designer to add additional visual styles.

If this.props.style is merged with the default styles, then I must have knowledge of what styles are defined, so that I may override them, rather than exposing an API that says "I dont care what styles are defined, please don't use them" (noDefaultStyles prop)

I'd like to see this implemented like @robmclarty suggested.

**Comment by paramaggarwal** [comment]
I think you misunderstood, when `this.props.style` is set, it completely overrides default styling, not merge.

**Comment by nickhudkins** [comment]
@paramaggarwal closing my computer now :(. I'm batting 0/2 today. Thanks for the clarification, and sorry for not looking into that deeper first.

**Comment by paramaggarwal** [comment]
@nickhudkins Thanks for debating this out. It's trivial to include one more prop, but its nice to question the need.

Hence suggesting the following here:

```
var style;
if (this.props.style) {
  style = this.props.style;
} else if (this.props.className) {
  style = {}
} else {
  style = {
    width: this.props.size || 100,
    height: this.props.size || 100,
    borderStyle: this.state.isDragActive ? 'solid' : 'dashed'
  }
};
```

**Comment by robmclarty** [comment]
@paramaggarwal you're right that this is simpler. I was originally concerned about allowing the user to be able to define both a custom `className` *and* a custom `style` prop used in conjunction. Your suggestion handles this case. Therefore I don't believe the extra `noDefaultStyles` prop is necessary.

I've updated my pull request to reflect this line of thinking such that 1) if a `style` prop exists, use that, 2) if no `style` prop exists, but a `className` prop exists, use an empty object for `style`, and 3) if no `style` or `className` props exist, use the default style object.
