### ISSUE TITLE
[Enhancement] Support mobile

### ISSUE THREAD

**Issue by aldeepaul** [paramaggarwal/react-dropzone#53]
Tried this on ios and pop up to select camera/camera roll does not appear.

**Comment by paramaggarwal** [comment]
Yes, we need help with making this compatible on mobile!

**Comment by redenz** [comment]
Changing the component from a div to a button seems to make mobile work

**Comment by paramaggarwal** [comment]
Feel free to open a pull request!

**Comment by paramaggarwal** [comment]
Oops, hit the close button by mistake.

**Comment by django-emerge** [comment]
Hey redenz, can you provide an example?  I tried your suggestion (div to button element) but then on click of the button, my entire page reloads.

Thanks.

**Comment by redenz** [comment]
Sent a new PR.

**Comment by paramaggarwal** [comment]
This library has no use on a mobile as there is no concept of drag and drop of files on mobile. To support file inputs, one can simply use a normal input tag. For this reason, I'll be closing this issue.

**Comment by esseb** [comment]
@paramaggarwal how about desktop touch screens? I could always use media queries to fall back to a normal input element on mobile, but I need to support larger touch screen devices also where no media queries will help.

**Comment by justinhoward** [comment]
I don't understand the reasoning "no use on mobile". Most sites are responsive, not mobile-only. They need to support both desktop and mobile. By not supporting mobile, you force the fallback implementation on the developer. That is not a trivial workaround. If the reasoning is that it's too hard, then fine, but there definitely is a use.

**Comment by okonet** [comment]
I think it's not clear how it should behave on mobile. Each developer might want slightly different behavior. Or am I wrong? What is your thought on it? Mind doing a PR?

**Comment by justinhoward** [comment]
@okonet Thanks for your response. I have to apologize. I did some tests, and it seems everything already works how I expected. Clicking the dropzone on iOS/Android opens the file browser as expected. The original text of this issue made me assume otherwise. Sorry for wasting your time.

I guess the next step above that would be to replace the UI or messaging when on a platform that does not support drag-and-drop. However, you're right that it would be hard to anticipate developers expectations for how that would work, and might be beyond the scope of this component.

**Comment by jnystrom** [comment]
on IOS, when i click on the dialog component, i can get to camera roll, but when I select them, I dont see the error toast, or success, or the "Submit" button enabled.  ideas?
