### ISSUE TITLE
Input props

### ISSUE THREAD

**Issue by svagi** [paramaggarwal/react-dropzone#60]
Input is standart html tag. There should be an option for passing props to input element **or** option for passing custom input element which you can clone/extend in DropZone component.

**Comment by paramaggarwal** [comment]
Why so?

**Comment by svagi** [comment]
Well, how do you add some custom attributes to input tag? For example if you want to add `required`, `disabled` attrubute or anything else... How can I achieve that?

**Comment by paramaggarwal** [comment]
Ah ok, but this library is more for the drag and drop aspect than the `input` field itself. The `input` field is only as a fall back for somebody clicking instead of dragging and dropping.

For example if you did set `required`, it would still show up as empty when someone dragged and dropped a file. Similarly setting `disabled` in `input` still does not disable the drag and drop feature.

**Comment by paramaggarwal** [comment]
Please don't rely directly on `input` - it only serves a secondary purpose to the main drag and drop feature of this library. For anything more advanced pertaining to `input`, it would be better to directly create your own `input`.

To achieve features like `required` and `disabled` - you can keep state of whether some files were dropped on the zone and do validation there.
